name: Main build

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    name: Build Amiga Project
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive  # Important for fetching ACE and the cross toolchains
    - name: Create out-dir
      run: mkdir /home/runner/work/ace-cmake-starter/ace-cmake-starter/game-build
    - name: Set permissions
      run: chmod 777 /home/runner/work/ace-cmake-starter/ace-cmake-starter/game-build
    - name: Build tools
      uses: docker://mirqqq/amiga-development:v0.4
      with:
        args: >
          /bin/sh -c "cd /github/workspace && ls -l && build_ace_tools.sh"
    - name: Build with custom Docker image
      uses: docker://mirqqq/amiga-development:v0.4
      with:
        args: >
          /bin/sh -c "cd game && 
                        cmake -B /github/workspace/game-build -DVSCODE_AMIGA_EXTENSION_PATH=/home/amiga/.vscode/extensions/bartmanabyss.amiga-debug-1.7.9 -DCMAKE_TOOLCHAIN_FILE=../AmigaCMakeCrossToolchains/m68k-bartman.cmake && 
                        cmake --build /github/workspace/game-build --target showcase.elf -j 6"
    - name: Build lha archive
      uses: docker://mirqqq/amiga-development:v0.4
      with:
        args: >
          /bin/sh -c "cd /github/workspace/game-build/dist &&
          lha a /github/workspace/game-build/game.lha data showcase.exe"
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: game
        path: /home/runner/work/ace-cmake-starter/ace-cmake-starter/game-build/game.lha
    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: /home/runner/work/ace-cmake-starter/ace-cmake-starter/game-build/game.lha