name: Main build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    name: Build Amiga Project
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive  # Important for fetching ACE and the cross toolchains
    
    - name: Build with custom Docker image
      uses: docker://mirqqq/amiga-development:v0.2
      with:
        args: >
          /bin/sh -c "cd game && 
                        cmake -B /home/amiga/projects/game-build -DVSCODE_AMIGA_EXTENSION_PATH=/home/amiga/.vscode/extensions/bartmanabyss.amiga-debug-1.7.9 -DCMAKE_TOOLCHAIN_FILE=../AmigaCMakeCrossToolchains/m68k-bartman.cmake && 
                        make -j$(nproc)"
